title: Molly-Ngampit Sutthasilp 
logo: "/images/logo.png?raw=true" 
description: > 
  <br></br>
  <br>I’m a detail oriented web-developer. I’m passionate about coding<br>
  <br></br>
  <br>I possess more than 12+ years of IT and engineering experience, with three recent years in BI development and data analytics in various industries. My strength and passion are in coding skills.  I am a quick learner and enjoy working as a team to overcome more significant challenges for its success and the company. <br>
  <a href="https://linkedin.com/in/mollyngampit/">View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 
